version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: secure_todo
      POSTGRES_PASSWORD: insecure-change-me
      POSTGRES_DB: secure_todo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - postgres
      - redis
    networks:
      - internal
    # فقط API را برای توسعه به host publish می‌کنیم
    ports:
      - "8081:8081"

networks:
  internal:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
